# Change these first
owner: agrez # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: SIHE Mail
    url: https://mail.sheridan.edu.au
  - name: SIHE Website
    url: https://www.sheridan.edu.au
  - name: SIHE Canvas
    url: https://canvas.sheridan.edu.au
  - name: SIHE UMS
    url: https://student.sheridan.edu.au
  - name: SIHE Library
    url: https://library.sheridan.edu.au

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime monitor**"
  introMessage: Always watching.... every 5 mins....
  navbar:
    - title: Status
      href: /
    #- title: GitHub
    #  href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
